spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: Dataui

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true
  sql:
    init:
      enabled:


logging:
  level:
    ROOT: ERROR
